# Generated by Django 3.1.7 on 2021-12-21 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('CourseId', models.AutoField(primary_key=True, serialize=False)),
                ('Number', models.CharField(max_length=50)),
                ('Title', models.CharField(max_length=150)),
                ('Section', models.CharField(max_length=50)),
                ('Type', models.CharField(max_length=50)),
                ('CreditHour', models.IntegerField()),
                ('StartTime', models.CharField(max_length=50)),
                ('EndTime', models.CharField(max_length=50)),
                ('DaysOfWeek', models.CharField(max_length=50)),
                ('Room', models.CharField(max_length=100)),
                ('Building', models.CharField(max_length=100)),
                ('Capacity', models.IntegerField()),
                ('Enrolled', models.IntegerField()),
                ('NRating', models.IntegerField()),
                ('AverageRating', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('DepartmentId', models.AutoField(primary_key=True, serialize=False)),
                ('DepartmentName', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('StudentId', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('UserName', models.CharField(max_length=50)),
                ('PassWord', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254, null=True)),
                ('TotalCredit', models.IntegerField()),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CourseManagement.department')),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('InstructorId', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('UserName', models.CharField(max_length=50)),
                ('PassWord', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254, null=True)),
                ('NRating', models.IntegerField()),
                ('AverageRating', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('TotalCredit', models.IntegerField()),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CourseManagement.department')),
            ],
        ),
        migrations.CreateModel(
            name='GiveRating',
            fields=[
                ('RatingId', models.AutoField(primary_key=True, serialize=False)),
                ('Rating', models.IntegerField()),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CourseManagement.course')),
                ('Instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CourseManagement.instructor')),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CourseManagement.student')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('EnrollmentId', models.AutoField(primary_key=True, serialize=False)),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CourseManagement.course')),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CourseManagement.student')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='Department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CourseManagement.department'),
        ),
        migrations.AddField(
            model_name='course',
            name='Instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CourseManagement.instructor'),
        ),
    ]
